### ISSUE TITLE
app / link page should have meta tags

### ISSUE THREAD

**Issue by gionatamettifogo** [instacard/instacard#121]
the link page should present the proper meta tags so it can be shown with its thumbnail image. maybe the way to do this is to build it server side w/o javascript and make it redirect to the app? let's discuss

**Comment by FSolfa** [comment]
https://create-react-app.dev/docs/title-and-meta-tags/#generating-dynamic-meta-tags-on-the-server

**Comment by gionatamettifogo** [comment]
@FSolfa let's create a page with fixed metadata that works well in whatsapp, facebook, instagram, etc. I will then make the server inject this meta in the index.html page for the /app/links/xxx path...

**Comment by gionatamettifogo** [comment]
per cortesia:
- crea la pagina statica
- testa che si veda bene su whatsapp, aggiungi screenshot
- testa che si veda bene su facebook, aggiungi screenshot
- testa che si veda bene su instagram, aggiungi screenshot
- committa la pagina statica
- rigira il ticket

**Comment by FSolfa** [comment]
![facebook](https://user-images.githubusercontent.com/6178824/85540280-191c2780-b617-11ea-9eab-3cb48dc91e34.jpg)
![imessage](https://user-images.githubusercontent.com/6178824/85540294-1b7e8180-b617-11ea-835c-1cbcec70f4ef.jpg)
![instagram](https://user-images.githubusercontent.com/6178824/85540299-1cafae80-b617-11ea-95f3-cecb5dcf7298.jpg)
![share](https://user-images.githubusercontent.com/6178824/85540304-1d484500-b617-11ea-8ee7-da0c7f5002c1.PNG)
![whatsapp](https://user-images.githubusercontent.com/6178824/85540314-1e797200-b617-11ea-8d57-689e864f9ced.jpg)

**Comment by FSolfa** [comment]
![IMG_4447](https://user-images.githubusercontent.com/6178824/85836221-9ae68f00-b796-11ea-8eed-2a4041aa50fc.jpg)
![IMG_4448](https://user-images.githubusercontent.com/6178824/85836229-9c17bc00-b796-11ea-95dd-8b8bd73938fd.jpg)

**Comment by gionatamettifogo** [comment]
Va controllato se e come funziona quando viene fatto sharing tra gli utenti
