### ISSUE TITLE
app / should use x-forwarded-host properly and only pass host name, not port

### ISSUE THREAD

**Issue by gionatamettifogo** [instacard/instacard#174]
// get forwarded host, used only in develop mode
function getForwardedHost() {
    if (process.env.NODE_ENV === "development" && process.env.HOST) {
        // TODO app / should use x-forwarded-host properly and only pass host name, not port #174
        return { "X-Forwarded-Host": process.env.HOST };
    }
}

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host

**Comment by FSolfa** [comment]
x-forwarded-host is added by react proxy.
remove getForwardedHost from api
