### ISSUE TITLE
app / skeleton stripe payment component

### ISSUE THREAD

**Issue by gionatamettifogo** [instacard/instacard#46]
/app/cards/xxx/products/

- list products
- next to each product add "Buy" button
- buy button 
     - creates stripe checkout session via POST /api/cards/xxx/products/xxx
     - calls stripe sdk to complete checkout transaction
     - goes back to /app/cards/xxx on success

**Comment by FSolfa** [comment]
ETA Friday / 2:50 pm

**Comment by gionatamettifogo** [comment]
é committato? come si accede alla pagina?
