### ISSUE TITLE
app / card component design

### ISSUE THREAD

**Issue by gionatamettifogo** [instacard/instacard#50]
- [x] card has same proportions as actual credit cards
- [x] card has QR code on the right side, vertically centered
- [x] height of QR code is 1/2 of height of card for now
- [x] card background from card/attributes/images[0]
- [x] rounded corners as in credit cards

**Comment by gionatamettifogo** [comment]
![image](https://user-images.githubusercontent.com/2813336/83406996-224b1780-a410-11ea-9b6f-09eb46fcc009.png)

**Comment by FSolfa** [comment]
ETA Monday / 14:20 pm
