### ISSUE TITLE
app / add presets, show transactions

### ISSUE THREAD

**Issue by gionatamettifogo** [instacard/instacard#54]
- [x] change customer name to Elisa Manelli, also in gmail
- [ ] add preset campaign with free espresso
- [ ] join campaign gain 1 free espresso
- [ ] drink free espresso
- [ ] add preset offer for "10 espressi" with description
- [ ] add preset to purchase offer
- [x] add 2 preset transactions to remove 1 espresso on different days
- [x] add "La mia carta"/"My card" header on top of card "cards-card-header" in localized strings
- [x] add "Saldi"/"Balances" on top of balances block, "cards-balances-header"
- [x] add balances, each line with [unit_amount] [currency] [gift button]
- [x] add "Transazioni"/"Transactions" on top of transactions block "cards-transactions-header""
- [x] list transactions with icon (fixed for now or lookup) name, description, date

**Comment by FSolfa** [comment]
_add balances, each line with [unit_amount] [currency] [gift button]_ **add buy botton?**
