### ISSUE TITLE
server / add store info in /api/cards/xxx

### ISSUE THREAD

**Issue by FSolfa** [instacard/instacard#66]
add store info in api card detail (location, phone, ...)

**Comment by FSolfa** [comment]
<img width="408" alt="Screenshot 2020-06-05 at 16 55 45" src="https://user-images.githubusercontent.com/6178824/83891446-75dd9e00-a74d-11ea-9a0e-efae97db8ba0.png">

**Comment by gionatamettifogo** [comment]
You can get the store information now, right? Do we still need this?
