### ISSUE TITLE
server / INSTACARD_DOMAIN need to be current host

### ISSUE THREAD

**Issue by FSolfa** [instacard/instacard#72]
We need to update INSTACARD_DOMAIN with current host.
Now Barrer token is set to instacart.it and when we log in with instacard.ngrok.it domain auth not working (see security.py at line 252).

**Comment by gionatamettifogo** [comment]
Me lo scriveresti in Italiano? Non ho capito bene se é il problema che abbiamo giá risolto con il cookie o qualcos'altro...

**Comment by FSolfa** [comment]
Sorry per l'inglese.
Nel file security.py at line 252 viene impostato il domain per la generazione del token. Ora è fisso su instacard.it, deve essere preso dell'host corrente altrimenti la login non funziona.

ES. su ngrok la login non va se li è impostato instacard.it perchè il domain non combacia con l'host e viene rifiutato dal browser.
