### ISSUE TITLE
app / find good qrcode scanner library

### ISSUE THREAD

**Issue by gionatamettifogo** [instacard/instacard#9]
find open source library in npm that:
- is active and has been active recently
- works well on android and ios phone
- works well with react

implement test page:
- /app/qr/scan
- top one third of the screen shows the scanning area
- below the scanning area shows the scanned content
- plays a simple beep sound when item is scanned

**Comment by FSolfa** [comment]
see https://github.com/cozmo/jsQR

**Comment by FSolfa** [comment]
ETA monday/11.00 am
